### PR TITLE
Create Update Row action for Baserow component

### LINKED ISSUE #1645: Baserow - Update Row action
Implement the Update Row action for the Baserow component to allow users to modify specific rows within a table in their Baserow database.

**Action properties:**
- table id - id of the table for which you want to update a row
- row id - id of the row you wish to update
- user_field_names - A boolean indicating whether the field names returned by this endpoint should be the actual names of the fields
- fields - a map of fields and their new values for the table. This property specifies the data to be updated in the row, allowing users to change multiple fields in a single operation.

**Ouput:**
- row -  updated row object containing all the data fields and values associated with the row in the specified table

Documentation Reference: https://baserow.io/api-docs

### PR DESCRIPTION
**Pull request by uday-rana**
## Description

Fixes #1645

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## How Has This Been Tested?

- Tested with BaserowComponentHandler definition test, which was updated to accommodate the new action.
- Manually tested action through client:

image

image

image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
  - No comments deemed necessary since the existing action doesn't include comments either
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by uday-rana** [comment]
Hi @monikakuster ,

I noticed a couple of things while working on this:

- I re-used `BaserowPropertiesUtils::createPropertiesForNewRow` since it already handles getting the properties for the row. It might make sense to rename this.
- The description for the Create Row action specifically refers to the dummy Projects table by name. This might need to be updated:

image

**Comment by monikakuster** [comment]
Hey, @uday-rana. Thanks for pointing these out! I'll take care of renaming BaserowPropertiesUtils::createPropertiesForNewRow to better reflect its broader usage. Regarding the description for the Create Row action, I'll review it and make the necessary updates.

**Comment by uday-rana** [comment]
Hi @monikakuster , I've added the test for the new action and the changes are ready for review.

I tried basing it on the test for the Create Row action but I'm not too familiar with Mockito and JUnit, so please let me know if something doesn't look right.

**Comment by monikakuster** [comment]
Hey, @uday-rana. Everything looks good.  I've made some refactoring changes...
 
 When you're ready to submit a PR, please make sure to target the develop branch instead of master. You can find detailed instructions on our contribution process in [here](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md#step-by-step-guide-to-contributing).
 
Additionally, it's a good practice to include the **issue number** at the beginning of your commit message, followed by a concise description of the changes made. This helps in tracking the progress of specific issues and provides context for the commit, making it easier for others to understand the purpose and scope of your changes.

For example: `1645 - create update row action for baserow component`.

You're welcome to start working on another issue. :smile:

**Pull request merged**
